-- Tablas históricas GHIN (ya aplicadas en producción como 20260812140908).
-- Archivo reconstruido desde el esquema vivo para que el repo coincida
-- con supabase_migrations.schema_migrations.

CREATE TABLE IF NOT EXISTS public.ghin_rounds (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ghin_number text NOT NULL,
  golfer_name text,
  gender text NOT NULL CHECK (gender = ANY (ARRAY['M'::text, 'F'::text])),
  date_played date NOT NULL,
  score_type text,
  tee_name text,
  tee_cr numeric(4, 1),
  tee_sr smallint,
  hi_at_play numeric(4, 1),
  course_handicap smallint,
  total_score smallint,
  differential numeric(4, 1),
  h1 smallint,
  h2 smallint,
  h3 smallint,
  h4 smallint,
  h5 smallint,
  h6 smallint,
  h7 smallint,
  h8 smallint,
  h9 smallint,
  h10 smallint,
  h11 smallint,
  h12 smallint,
  h13 smallint,
  h14 smallint,
  h15 smallint,
  h16 smallint,
  h17 smallint,
  h18 smallint,
  source_file text,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (ghin_number, date_played, tee_name, total_score)
);

CREATE INDEX IF NOT EXISTS idx_ghin_rounds_ghin_date
  ON public.ghin_rounds (ghin_number, date_played DESC);
CREATE INDEX IF NOT EXISTS idx_ghin_rounds_date
  ON public.ghin_rounds (date_played DESC);
CREATE INDEX IF NOT EXISTS idx_ghin_rounds_type
  ON public.ghin_rounds (score_type);

CREATE TABLE IF NOT EXISTS public.ghin_index_revisions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ghin_number text NOT NULL,
  golfer_name text,
  revision_date date NOT NULL,
  handicap_index numeric(4, 1),
  source_file text,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (ghin_number, revision_date)
);

CREATE INDEX IF NOT EXISTS idx_ghin_rev_ghin_date
  ON public.ghin_index_revisions (ghin_number, revision_date DESC);

CREATE TABLE IF NOT EXISTS public.ghin_competition_rounds (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ghin_number text NOT NULL,
  golfer_name text,
  gender text,
  score_type text NOT NULL,
  date_played date NOT NULL,
  ags smallint,
  course_rating numeric(4, 1),
  slope_rating smallint,
  differential numeric(4, 1),
  course_played text,
  used boolean,
  source_file text,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (ghin_number, date_played, course_played, ags)
);

CREATE INDEX IF NOT EXISTS idx_ghin_comp_ghin
  ON public.ghin_competition_rounds (ghin_number, date_played DESC);
CREATE INDEX IF NOT EXISTS idx_ghin_comp_course
  ON public.ghin_competition_rounds (course_played);
